[window]
padding = { x = 10, y = 10}
decorations = "Full"

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Normal"}
bold = { family = "JetbrainsMono Nerd Font", style = "Bold"}
size = 20


[selection]
save_to_clipboard = true
